# Generated by Django 3.2.13 on 2022-05-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepassword',
            name='url',
            field=models.URLField(default='https://google.com/'),
        ),
    ]
